### ISSUE TITLE
About the calculation of the Jacob.

### ISSUE THREAD

**Issue by ShunLu91** [BayesWatch/nas-without-training#17]
First, thanks for your nice work!
But I have a question that when you calculate the Jacob and you multiply the output with an all-one matrix to get a scalar. 
For example, when the batch_size=1,  the input shape is 32x32x1 (flatten to 1024), and the output shape is 10. By definition, we should solve the gradient of each output with respect to the input, so we get a Jacob matrix of 10x1024. However, when you multiply the output with an all-one matrix to get a scalar, you can only get a Jacob matrix with shape 1x1024. 
Hence, what does this scalar mean? And are these two matrices(10x1024 vs 1x1024) equivalent?
Best wishes and look forward to your reply.

**Comment by jack-willturner** [comment]
Apologies for never getting back to you on this --- we have now (since v1) simplified the score to no longer use the Jacobian, so I'm going to close this issue. 

However to answer your question - we always set the number of output units to be one (e.g. https://github.com/BayesWatch/nas-without-training/blob/master/nasspace.py#L26), so it's 1x1024 instead of 10x1024.
