### ISSUE TITLE
analyze about imagenet-1k 

### ISSUE THREAD

**Issue by lucienne999** [BayesWatch/nas-without-training#8]
Hi, I am confused that what's happened if the input size becomes larger, e.g. 224. Under this condition, the dimension of Jacob matrix becomes 3x224x224 (after flatten)
 
Is your work failed when the Jacob matrix dimension becomes very large?

**Comment by jack-willturner** [comment]
Hi,

This is something we didn’t have the data to try easily since there isn’t a curated NAS-benchmark for large images. 

We assume that the method will continue to work, but don’t have any strong empirical evidence due to the expense of training large numbers of ImageNet-sized models. 

This is certainly something we would be interested in but will have to come back to once there is an accepted ImageNet NAS bench.
