### ISSUE TITLE
Question about development of score when network is trained

### ISSUE THREAD

**Issue by simonhessner** [BayesWatch/nas-without-training#9]
Just out of interest, did you also measure the scores when actually training the networks after each epoch? How do they develop?

I was wondering if the scores are even more correlated to the final model's accuracy when they are measured not directly after initialization but after 1 or 2 epochs.

**Comment by jack-willturner** [comment]
Hi 

This is an interesting question, and something we're aiming to investigate in the future. Since we don't have access to the model weights at different points during the training through the NAS-Bench-201 API, it's quite hard to answer. 

I think the best way to go about testing will be to just train a subset of the networks. When we get round to it I will re-open this issue!

Thanks,

Jack
